package main

import (
	"fmt"
	"sort"
	"strings"
)

// capability is the one vocabulary used by project toggles, library
// requirements, and target resolution. Each row says which owners must
// provide evidence before the capability is available. A toggleable row must
// have a profile macro and header override; sdkconfig may only supplement it.
type capability struct {
	name            string
	needsBoard      bool
	boardPeripheral bool
	needsTarget     bool
	profileMacro    string
	toggleable      bool
	offDefines      []string
	offSdkconfig    []string
}

var capabilities = []capability{
	{name: "adc", needsBoard: true, boardPeripheral: true, needsTarget: true},
	{
		name:            "ble",
		needsBoard:      true,
		boardPeripheral: true,
		needsTarget:     true,
		profileMacro:    "FR_FEATURE_BLE",
		toggleable:      true,
		offDefines:      []string{"#define FR_FEATURE_BLE 0"},
		offSdkconfig:    []string{"CONFIG_BT_ENABLED=n"},
	},
	{name: "cells", profileMacro: "FR_FEATURE_CELLS"},
	{name: "dual_core", needsBoard: true},
	{name: "gpio", needsBoard: true, boardPeripheral: true, needsTarget: true},
	{name: "i2c", needsBoard: true, boardPeripheral: true, needsTarget: true, profileMacro: "FR_FEATURE_I2C"},
	{name: "i2s", needsBoard: true, boardPeripheral: true, needsTarget: true},
	{
		// No sdkconfig lines: with FR_FEATURE_NET 0 nothing references
		// esp_wifi/lwip, so the linker drops them (measured on esp32_devkit_v1:
		// -608 KiB flash). Wi-Fi reserves no static RAM until initialized, so
		// unlike BLE there is no controller config to flip.
		name:            "net",
		needsBoard:      true,
		boardPeripheral: true,
		needsTarget:     true,
		profileMacro:    "FR_FEATURE_NET",
		toggleable:      true,
		offDefines:      []string{"#define FR_FEATURE_NET 0"},
	},
	{name: "pwm", needsBoard: true, boardPeripheral: true, needsTarget: true, profileMacro: "FR_FEATURE_PWM"},
	{name: "text", profileMacro: "FR_FEATURE_TEXT"},
	{name: "uart", needsBoard: true, boardPeripheral: true, needsTarget: true, profileMacro: "FR_FEATURE_UART"},
}

func isKnownCapability(name string) bool {
	_, ok := capabilityByName(name)
	return ok
}

func capabilityByName(name string) (capability, bool) {
	for _, c := range capabilities {
		if c.name == name {
			return c, true
		}
	}
	return capability{}, false
}

// validateCapabilities accepts only composition toggles. Non-boolean values
// are already rejected by TOML decoding into map[string]bool. An explicit
// true requests the profile default and is still subject to target resolution.
func validateCapabilities(selected map[string]bool) error {
	for name := range selected {
		c, ok := capabilityByName(name)
		if !ok {
			return fmt.Errorf("unknown capability %q; offered: %s", name, offeredCapabilityNames())
		}
		if !c.toggleable {
			return fmt.Errorf("capability %q is not configurable; offered: %s",
				name, offeredCapabilityNames())
		}
	}
	return nil
}

// disabledCapabilities returns the offered capabilities set to false, sorted
// by name so generated files are stable across runs.
func disabledCapabilities(selected map[string]bool) []capability {
	var out []capability
	for name, enabled := range selected {
		if enabled {
			continue
		}
		if c, ok := capabilityByName(name); ok && c.toggleable {
			out = append(out, c)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].name < out[j].name })
	return out
}

func generatedCompositionH(disabled []capability) string {
	var b strings.Builder
	b.WriteString("/* Generated by frothy build. Do not edit. */\n")
	for _, c := range disabled {
		for _, line := range c.offDefines {
			b.WriteString(line)
			b.WriteByte('\n')
		}
	}
	return b.String()
}

func generatedCompositionSdkconfig(disabled []capability) string {
	var b strings.Builder
	b.WriteString("# Generated by frothy build. Do not edit.\n")
	for _, c := range disabled {
		for _, line := range c.offSdkconfig {
			b.WriteString(line)
			b.WriteByte('\n')
		}
	}
	return b.String()
}

func offeredCapabilityNames() string {
	var names []string
	for _, c := range capabilities {
		if c.toggleable {
			names = append(names, c.name)
		}
	}
	sort.Strings(names)
	return strings.Join(names, ", ")
}
