package main

import (
	"strings"
	"testing"
)

func testTargetContract(board string,
	unavailable map[string]capabilityReason) targetContract {
	statuses := make(map[string]capabilityStatus, len(capabilities))
	for _, c := range capabilities {
		statuses[c.name] = capabilityStatus{available: true}
	}
	for name, reason := range unavailable {
		statuses[name] = capabilityStatus{reason: reason}
	}
	return targetContract{board: board, capabilities: statuses}
}

func TestValidateCapabilitiesUnknownName(t *testing.T) {
	err := validateCapabilities(map[string]bool{"warp-drive": false})
	if err == nil || !strings.Contains(err.Error(), `unknown capability "warp-drive"`) {
		t.Fatalf("want unknown-capability error, got %v", err)
	}
}

func TestToggleableCapabilitiesHaveHeaderEvidence(t *testing.T) {
	for _, c := range capabilities {
		if c.toggleable && (c.profileMacro == "" || len(c.offDefines) == 0) {
			t.Errorf("%s toggle lacks profile macro or header override", c.name)
		}
		if c.boardPeripheral && !c.needsBoard {
			t.Errorf("%s is a peripheral without board evidence", c.name)
		}
	}
}

// cells is a known requirement target but NOT an offered composition toggle.
// Project validation must reject it, guarding against a slip to isKnownCapability
// that would let a manifest disable an always-on feature.
func TestValidateCapabilitiesRejectsKnownButNotOffered(t *testing.T) {
	err := validateCapabilities(map[string]bool{"cells": false})
	if err == nil || !strings.Contains(err.Error(), `capability "cells" is not configurable`) {
		t.Fatalf("want cells rejected as not-offered, got %v", err)
	}
}

func TestValidateCapabilitiesKnownIsAccepted(t *testing.T) {
	if err := validateCapabilities(map[string]bool{"ble": false}); err != nil {
		t.Fatalf("ble off must be accepted: %v", err)
	}
	if err := validateCapabilities(map[string]bool{"ble": true}); err != nil {
		t.Fatalf("ble on request must be accepted for later resolution: %v", err)
	}
	if err := validateCapabilities(map[string]bool{"net": false}); err != nil {
		t.Fatalf("net off must be accepted: %v", err)
	}
}

// i2s is a requirement target (frothy-synth needs it) but never a toggle.
func TestI2sIsKnownButNotOffered(t *testing.T) {
	if !isKnownCapability("i2s") {
		t.Fatal("i2s must be a known requirement target")
	}
	err := validateCapabilities(map[string]bool{"i2s": false})
	if err == nil || !strings.Contains(err.Error(), `capability "i2s" is not configurable`) {
		t.Fatalf("want i2s rejected as not-offered, got %v", err)
	}
}

// net's off-bundle is header-only: the linker drops the unreferenced Wi-Fi
// stack, and there is no controller sdkconfig to flip (unlike ble).
func TestGeneratedCompositionFilesForNet(t *testing.T) {
	disabled := disabledCapabilities(map[string]bool{"net": false})
	gotH := generatedCompositionH(disabled)
	wantH := "/* Generated by frothy build. Do not edit. */\n" +
		"#define FR_FEATURE_NET 0\n"
	if gotH != wantH {
		t.Fatalf("composition.h mismatch:\n%q\nwant\n%q", gotH, wantH)
	}
	gotSdk := generatedCompositionSdkconfig(disabled)
	wantSdk := "# Generated by frothy build. Do not edit.\n"
	if gotSdk != wantSdk {
		t.Fatalf("composition sdkconfig mismatch:\n%q\nwant\n%q", gotSdk, wantSdk)
	}
}

func TestDisabledCapabilitiesSortsBleBeforeNet(t *testing.T) {
	disabled := disabledCapabilities(map[string]bool{"net": false, "ble": false})
	if len(disabled) != 2 || disabled[0].name != "ble" || disabled[1].name != "net" {
		t.Fatalf("want [ble net], got %v", disabled)
	}
}

func TestDisabledCapabilitiesSkipsEnabledAndSorts(t *testing.T) {
	disabled := disabledCapabilities(map[string]bool{"ble": false})
	if len(disabled) != 1 || disabled[0].name != "ble" {
		t.Fatalf("want [ble] disabled, got %v", disabled)
	}
	if got := disabledCapabilities(map[string]bool{"ble": true}); len(got) != 0 {
		t.Fatalf("an enabled capability must not appear as disabled, got %v", got)
	}
}

func TestGeneratedCompositionH(t *testing.T) {
	got := generatedCompositionH(disabledCapabilities(map[string]bool{"ble": false}))
	want := "/* Generated by frothy build. Do not edit. */\n" +
		"#define FR_FEATURE_BLE 0\n"
	if got != want {
		t.Fatalf("composition.h mismatch:\n%q\nwant\n%q", got, want)
	}
}

func TestGeneratedCompositionSdkconfig(t *testing.T) {
	got := generatedCompositionSdkconfig(disabledCapabilities(map[string]bool{"ble": false}))
	want := "# Generated by frothy build. Do not edit.\nCONFIG_BT_ENABLED=n\n"
	if got != want {
		t.Fatalf("composition sdkconfig mismatch:\n%q\nwant\n%q", got, want)
	}
}
