/*
 * Plain roomier ESP-IDF profile.
 *
 * Official ESP32 boards share this 32-bit tagged word contract. It gives
 * on-device source, names, cells, and NVS persistence enough room to be useful
 * over the board-selected human serial console.
 */

#pragma once

#define FR_WORD_SIZE 32

#define FR_PROFILE_TARGET_FLASH_BYTES 4194304u
#define FR_PROFILE_TARGET_SRAM_BYTES 327680u
#define FR_PROFILE_MIN_STACK_RESERVE_BYTES 24576u

#define FR_PROFILE_MAX_SLOTS 512
#define FR_PROFILE_TOTAL_IMAGE_BYTES 1024
#define FR_PROFILE_MAX_DEFINITION_INSTRUCTION_BYTES 1024
#define FR_PROFILE_MAX_DEFINITION_TEXT_BYTES 4096
#define FR_PROFILE_MAX_DEFINITION_CODE_OBJECTS 2
#define FR_PROFILE_MAX_OVERLAY_CODE_BYTES 1024
#define FR_PROFILE_MAX_OVERLAY_TEXT_BYTES 4096
#define FR_PROFILE_MAX_OVERLAY_PARAM_NAME_BYTES 520
#define FR_PROFILE_MAX_SOURCE_RENDER_BYTES 4096
#define FR_PROFILE_MAX_STACK_DEPTH 48
#define FR_PROFILE_CODE_OBJECT_TABLE_SIZE 512
#define FR_PROFILE_NATIVE_TABLE_SIZE 163
#define FR_PROFILE_MAX_HANDLES 16
#define FR_PROFILE_OBJECT_TABLE_SIZE 128
#define FR_PROFILE_MAX_CELL_WORDS 128
#define FR_PROFILE_MAX_CELL_LENGTH 32
#define FR_PROFILE_MAX_TEXT_BYTES 8192
#define FR_PROFILE_MAX_TEXT_LENGTH 4096
#define FR_PROFILE_MAX_RECORD_NAME_BYTES 256
#define FR_PROFILE_MAX_RECORD_FIELDS_PER_SHAPE 4
#define FR_PROFILE_MAX_RECORD_SHAPE_FIELDS 32
#define FR_PROFILE_MAX_RECORD_VALUE_FIELDS 64
#define FR_PROFILE_MAX_CALL_DEPTH 24
#define FR_PROFILE_MAX_ATTEMPT_DEPTH 4
#define FR_PROFILE_PERSISTENCE_BYTES 4096
#define FR_PROFILE_PERSIST_STORAGE_BYTES 65535
#define FR_PROFILE_MAX_NAME_BYTES 48
#define FR_PROFILE_PARSE_MAX_TOKEN_BYTES 64
#define FR_PROFILE_PARSE_MAX_EXPR_DEPTH 16
#define FR_PROFILE_PARSE_MAX_EXPR_NODES 64
#define FR_PROFILE_PARSE_MAX_BODY_EXPRS 24
#define FR_PROFILE_PARSE_MAX_PARAMS 8
#define FR_PROFILE_PARSE_MAX_LOCALS 16
#define FR_PROFILE_MAX_OVERLAY_NAMES 256
#define FR_PROFILE_REPL_LINE_BYTES 512
#define FR_BASE_IMAGE_INCLUDE_SYMBOLS 1

#define FR_FEATURE_REPL 1
#define FR_FEATURE_COMPILER 1
#define FR_FEATURE_PERSISTENCE 1
#define FR_FEATURE_INTROSPECTION 1
#define FR_FEATURE_CELLS 1
#define FR_FEATURE_TEXT 1
#define FR_FEATURE_RECORDS 1
#define FR_FEATURE_HANDLES 1
#define FR_FEATURE_UART 1
#define FR_FEATURE_CONSOLE_ROUTING 1
#ifndef FR_FEATURE_NET
#define FR_FEATURE_NET 1
#endif
#define FR_FEATURE_POWER 1
#define FR_FEATURE_BYTES 1
#define FR_FEATURE_PAD 1
#define FR_FEATURE_TRACE 1
#define FR_FEATURE_PULSE 1
#ifndef FR_FEATURE_BLE
#define FR_FEATURE_BLE 1
#endif

#if FR_FEATURE_BLE
#define FR_BLE_ENABLE_OBSERVER 1
#define FR_BLE_ENABLE_BROADCASTER 1
#define FR_BLE_ENABLE_CENTRAL 1
#define FR_BLE_ENABLE_PERIPHERAL 1
#define FR_BLE_ENABLE_GATT_SERVER 1
#define FR_BLE_ENABLE_GATT_CLIENT 1
#define FR_BLE_SCAN_QUEUE_COUNT 8
#define FR_BLE_SCAN_DATA_BYTES 31
#define FR_BLE_ADVERTISEMENT_DATA_BYTES 31
#define FR_BLE_CONNECTION_COUNT 1
#define FR_BLE_PENDING_CONNECTION_COUNT 1
#define FR_BLE_CONNECTION_NOTICE_COUNT 4
#define FR_BLE_CONNECT_TIMEOUT_MAX_MS 60000
#define FR_BLE_START_TIMEOUT_MS 5000
#define FR_BLE_STOP_TIMEOUT_MS 1000
#define FR_BLE_GATT_SERVICE_COUNT 2
#define FR_BLE_GATT_CHARACTERISTIC_COUNT 6
#define FR_BLE_GATT_VALUE_BYTES 256
#define FR_BLE_GATT_WRITE_QUEUE_COUNT 4
#define FR_BLE_GATT_WRITE_DATA_BYTES 64
#define FR_BLE_GATT_CCCD_COUNT 2
#define FR_BLE_GATT_CLIENT_CACHE_COUNT 4
#define FR_BLE_GATT_CLIENT_DATA_BYTES 20
#define FR_BLE_GATT_NOTIFICATION_QUEUE_COUNT 4
#define FR_BLE_GATT_CLIENT_TIMEOUT_MAX_MS 60000
#endif /* FR_FEATURE_BLE */

#define FR_PROFILE_PAD_BYTES 64

#define FR_PROFILE_BYTES_COUNT 8
#define FR_PROFILE_BYTES_ARENA_BYTES 4096

#define FR_HTTP_MAX_BODY 4096
#define FR_TCP_HANDLE_COUNT 4
#define FR_TCP_LISTENER_COUNT 1
