/*
 * Roomier host proof profile for normal Frothy.
 *
 * This profile keeps the same device-owned compiler/runtime path as the small
 * host pressure profile, but gives the normal language enough room to prove
 * names, code, persistence, boot, inspection, and interrupt without Uno limits.
 */

#pragma once

#define FR_WORD_SIZE 32

#define FR_PROFILE_MAX_SLOTS 384
#define FR_PROFILE_TOTAL_IMAGE_BYTES 512
#define FR_PROFILE_MAX_DEFINITION_INSTRUCTION_BYTES 512
#define FR_PROFILE_MAX_DEFINITION_TEXT_BYTES 4096
#define FR_PROFILE_MAX_DEFINITION_CODE_OBJECTS 2
#define FR_PROFILE_MAX_OVERLAY_CODE_BYTES 512
#define FR_PROFILE_MAX_OVERLAY_TEXT_BYTES 4096
#define FR_PROFILE_MAX_OVERLAY_PARAM_NAME_BYTES 520
#define FR_PROFILE_MAX_SOURCE_RENDER_BYTES 2048
#define FR_PROFILE_MAX_STACK_DEPTH 32
#define FR_PROFILE_CODE_OBJECT_TABLE_SIZE 384
#if FR_BLE_ENABLE_GATT_CLIENT
#define FR_PROFILE_NATIVE_TABLE_SIZE 155
#elif FR_FEATURE_BLE
#define FR_PROFILE_NATIVE_TABLE_SIZE 147
#else
#define FR_PROFILE_NATIVE_TABLE_SIZE 129
#endif
#define FR_PROFILE_MAX_HANDLES 16
#define FR_PROFILE_OBJECT_TABLE_SIZE 96
#define FR_PROFILE_MAX_CELL_WORDS 64
#define FR_PROFILE_MAX_CELL_LENGTH 16
#define FR_PROFILE_MAX_TEXT_BYTES 65535
#define FR_PROFILE_MAX_TEXT_LENGTH 16384
#define FR_PROFILE_MAX_RECORD_NAME_BYTES 256
#define FR_PROFILE_MAX_RECORD_FIELDS_PER_SHAPE 4
#define FR_PROFILE_MAX_RECORD_SHAPE_FIELDS 32
#define FR_PROFILE_MAX_RECORD_VALUE_FIELDS 64
#define FR_PROFILE_PAD_BYTES 64
#define FR_PROFILE_MAX_CALL_DEPTH 16
#define FR_PROFILE_MAX_ATTEMPT_DEPTH 8
#define FR_PROFILE_PERSISTENCE_BYTES 4096
#define FR_PROFILE_PERSIST_STORAGE_BYTES 65535
#define FR_PROFILE_MAX_NAME_BYTES 48
#define FR_PROFILE_PARSE_MAX_TOKEN_BYTES 64
#define FR_PROFILE_PARSE_MAX_EXPR_DEPTH 16
#define FR_PROFILE_PARSE_MAX_EXPR_NODES 64
#define FR_PROFILE_PARSE_MAX_BODY_EXPRS 24
#define FR_PROFILE_PARSE_MAX_PARAMS 8
#define FR_PROFILE_PARSE_MAX_LOCALS 16
#define FR_PROFILE_MAX_OVERLAY_NAMES 192
#define FR_PROFILE_REPL_LINE_BYTES 512
#define FR_BASE_IMAGE_INCLUDE_SYMBOLS 1

#define FR_FEATURE_REPL 1
#define FR_FEATURE_COMPILER 1
#define FR_FEATURE_PERSISTENCE 1
#define FR_FEATURE_INTROSPECTION 1
#define FR_FEATURE_CELLS 1
#define FR_FEATURE_TEXT 1
#define FR_FEATURE_RECORDS 1
#define FR_FEATURE_HANDLES 1
#define FR_FEATURE_UART 1
#define FR_FEATURE_PAD 1
#define FR_FEATURE_NET 1
#define FR_FEATURE_POWER 1
#define FR_FEATURE_BYTES 1
#define FR_FEATURE_TRACE 1
#define FR_FEATURE_PULSE 1

#define FR_PROFILE_BYTES_COUNT 8
#define FR_PROFILE_BYTES_ARENA_BYTES 4096

#define FR_HTTP_MAX_BODY 16384
#define FR_TCP_HANDLE_COUNT 4
