/*
 * Plain RP2040 profile.
 *
 * The Nano RP2040 Connect has enough room for the normal live language, while
 * its first port stays focused on local device work: USB serial, persistence,
 * GPIO, ADC, PWM, and I2C. The NINA radio is not part of this profile.
 */

#pragma once

#define FR_WORD_SIZE 32

#define FR_PROFILE_TARGET_FLASH_BYTES 16777216u
#define FR_PROFILE_TARGET_SRAM_BYTES 270336u
#define FR_PROFILE_MIN_STACK_RESERVE_BYTES 16384u

#define FR_PROFILE_MAX_SLOTS 384
#define FR_PROFILE_TOTAL_IMAGE_BYTES 1024
#define FR_PROFILE_MAX_DEFINITION_INSTRUCTION_BYTES 1024
#define FR_PROFILE_MAX_DEFINITION_TEXT_BYTES 4096
#define FR_PROFILE_MAX_DEFINITION_CODE_OBJECTS 2
#define FR_PROFILE_MAX_OVERLAY_CODE_BYTES 1024
#define FR_PROFILE_MAX_OVERLAY_TEXT_BYTES 4096
#define FR_PROFILE_MAX_OVERLAY_PARAM_NAME_BYTES 520
#define FR_PROFILE_MAX_SOURCE_RENDER_BYTES 4096
#define FR_PROFILE_MAX_STACK_DEPTH 48
#define FR_PROFILE_CODE_OBJECT_TABLE_SIZE 384
#if FR_FEATURE_BLE
#define FR_PROFILE_NATIVE_TABLE_SIZE 146
#else
#define FR_PROFILE_NATIVE_TABLE_SIZE 128
#endif
#define FR_PROFILE_MAX_HANDLES 12
#define FR_PROFILE_OBJECT_TABLE_SIZE 96
#define FR_PROFILE_MAX_CELL_WORDS 128
#define FR_PROFILE_MAX_CELL_LENGTH 32
#define FR_PROFILE_MAX_TEXT_BYTES 8192
#define FR_PROFILE_MAX_TEXT_LENGTH 4096
#define FR_PROFILE_MAX_RECORD_NAME_BYTES 256
#define FR_PROFILE_MAX_RECORD_FIELDS_PER_SHAPE 4
#define FR_PROFILE_MAX_RECORD_SHAPE_FIELDS 32
#define FR_PROFILE_MAX_RECORD_VALUE_FIELDS 64
#define FR_PROFILE_MAX_CALL_DEPTH 24
#define FR_PROFILE_MAX_ATTEMPT_DEPTH 4
#define FR_PROFILE_PERSISTENCE_BYTES 4096
#define FR_PROFILE_PERSIST_STORAGE_BYTES 32768
#define FR_PROFILE_MAX_NAME_BYTES 48
#define FR_PROFILE_PARSE_MAX_TOKEN_BYTES 64
#define FR_PROFILE_PARSE_MAX_EXPR_DEPTH 16
#define FR_PROFILE_PARSE_MAX_EXPR_NODES 64
#define FR_PROFILE_PARSE_MAX_BODY_EXPRS 24
#define FR_PROFILE_PARSE_MAX_PARAMS 8
#define FR_PROFILE_PARSE_MAX_LOCALS 16
#define FR_PROFILE_MAX_OVERLAY_NAMES 192
#define FR_PROFILE_REPL_LINE_BYTES 512
#define FR_BASE_IMAGE_INCLUDE_SYMBOLS 1

#define FR_FEATURE_REPL 1
#define FR_FEATURE_COMPILER 1
#define FR_FEATURE_PERSISTENCE 1
#define FR_FEATURE_INTROSPECTION 1
#define FR_FEATURE_CELLS 1
#define FR_FEATURE_TEXT 1
#define FR_FEATURE_RECORDS 1
#define FR_FEATURE_HANDLES 1
#define FR_FEATURE_UART 0
#define FR_FEATURE_CONSOLE_ROUTING 0
#ifndef FR_FEATURE_NET
#define FR_FEATURE_NET 0
#endif
#define FR_FEATURE_POWER 0
#define FR_FEATURE_BYTES 1
#define FR_FEATURE_PAD 1
#define FR_FEATURE_EVENTS 0
#define FR_FEATURE_TRACE 0
#define FR_FEATURE_PULSE 0
#ifndef FR_FEATURE_BLE
#define FR_FEATURE_BLE 0
#endif

#define FR_PROFILE_PAD_BYTES 64

#define FR_PROFILE_BYTES_COUNT 8
#define FR_PROFILE_BYTES_ARENA_BYTES 4096
