#!/bin/sh

set -eu

repo_root=$(CDPATH= cd -- "$(dirname "$0")/../.." && pwd)
base_file="$repo_root/boards/esp32-devkit-v4-game-board/lib/base.frothy"
workshop_dir="$repo_root/workshop"
workshop_file="$workshop_dir/pong.frothy"

usage() {
  cat <<'EOF'
usage: export_workshop_repo.sh [write|check]

write  regenerate workshop/pong.frothy from the canonical v4 board base image
check  fail if workshop/pong.frothy has drifted from the canonical export
EOF
}

extract_pong_region() {
  awk '
    /^demo\.pong\.left is 0$/ { in_region = 1 }
    in_region { print }
    END {
      if (!in_region) {
        exit 2
      }
    }
  ' "$base_file"
}

render_export() {
  printf '\\ Exported from boards/esp32-devkit-v4-game-board/lib/base.frothy.\n'
  printf '\\ Do not edit this file directly in the Frothy repo; update base.frothy and rerun tools/frothy/export_workshop_repo.sh.\n'
  printf '\n'
  extract_pong_region
}

write_export() {
  tmp_file=$(mktemp "${TMPDIR:-/tmp}/frothy-workshop-pong.XXXXXX")
  trap 'rm -f "$tmp_file"' EXIT INT TERM
  mkdir -p "$workshop_dir"
  render_export > "$tmp_file"
  mv "$tmp_file" "$workshop_file"
}

check_export() {
  tmp_file=$(mktemp "${TMPDIR:-/tmp}/frothy-workshop-pong.XXXXXX")
  trap 'rm -f "$tmp_file"' EXIT INT TERM
  render_export > "$tmp_file"

  if [ ! -f "$workshop_file" ]; then
    printf 'missing workshop export: %s\n' "$workshop_file" >&2
    printf 'run: sh tools/frothy/export_workshop_repo.sh write\n' >&2
    exit 1
  fi

  if ! cmp -s "$tmp_file" "$workshop_file"; then
    printf 'workshop export drift: %s\n' "$workshop_file" >&2
    diff -u "$workshop_file" "$tmp_file" >&2 || true
    printf 'run: sh tools/frothy/export_workshop_repo.sh write\n' >&2
    exit 1
  fi
}

mode=${1:-write}
case "$mode" in
  write)
    write_export
    ;;
  check)
    check_export
    ;;
  -h|--help|help)
    usage
    ;;
  *)
    usage >&2
    exit 1
    ;;
esac
