#pragma once

#include <stdbool.h>

#include "image.h"
#include "native.h"
#include "types.h"

enum {
  FR_SLOT_BOOT = 0,
  FR_SLOT_WAIT = 1,
  FR_SLOT_ONE = 2,
  FR_SLOT_GPIO_WRITE = 3,
  FR_SLOT_LED_BUILTIN = 4,
  FR_SLOT_SAVE = 5,
  FR_SLOT_RESTORE = 6,
  FR_SLOT_WIPE = 7,
  FR_SLOT_GPIO_MODE = 8,
  FR_SLOT_GPIO_READ = 9,
  FR_SLOT_ADC_READ = 10,
  FR_SLOT_ADC_ABOVE = 11,
  FR_SLOT_MILLIS = 12,
  FR_SLOT_MICROS = 13,
#if FR_FEATURE_UART
  FR_SLOT_UART_OPEN = 14,
  FR_SLOT_UART_OPEN_ON = 15,
  FR_SLOT_UART_WRITE_BYTE = 16,
  FR_SLOT_UART_READ_BYTE = 17,
  FR_SLOT_UART_AVAILABLE = 18,
  FR_SLOT_UART_CLOSE = 19,
  FR_SLOT_BAUD_9600 = 20,
  FR_SLOT_BAUD_19200 = 21,
  FR_SLOT_BAUD_38400 = 22,
  FR_SLOT_BAUD_57600 = 23,
  FR_SLOT_BAUD_115200 = 24,
  FR_SLOT_BAUD_1200 = 25,
  FR_SLOT_AFTER_UART = 26,
#else
  FR_SLOT_AFTER_UART = 14,
#endif
#if FR_FEATURE_RANDOM
  FR_SLOT_RANDOM_NEXT = FR_SLOT_AFTER_UART,
  FR_SLOT_RANDOM_BELOW = FR_SLOT_AFTER_UART + 1,
  FR_SLOT_RANDOM_SEED = FR_SLOT_AFTER_UART + 2,
  FR_SLOT_AFTER_RANDOM = FR_SLOT_AFTER_UART + 3,
#else
  FR_SLOT_AFTER_RANDOM = FR_SLOT_AFTER_UART,
#endif
#if FR_FEATURE_PWM
  FR_SLOT_PWM_OPEN = FR_SLOT_AFTER_RANDOM,
  FR_SLOT_PWM_WRITE = FR_SLOT_AFTER_RANDOM + 1,
  FR_SLOT_PWM_CLOSE = FR_SLOT_AFTER_RANDOM + 2,
  FR_SLOT_AFTER_PWM = FR_SLOT_AFTER_RANDOM + 3,
#else
  FR_SLOT_AFTER_PWM = FR_SLOT_AFTER_RANDOM,
#endif
#if FR_FEATURE_I2C
  FR_SLOT_I2C_OPEN = FR_SLOT_AFTER_PWM,
  FR_SLOT_I2C_WRITE = FR_SLOT_AFTER_PWM + 1,
  FR_SLOT_I2C_READ = FR_SLOT_AFTER_PWM + 2,
  FR_SLOT_I2C_CLOSE = FR_SLOT_AFTER_PWM + 3,
  FR_SLOT_I2C_READ_REG = FR_SLOT_AFTER_PWM + 4,
  FR_SLOT_I2C_READ_REG16 = FR_SLOT_AFTER_PWM + 5,
  FR_SLOT_I2C_WRITE_REG = FR_SLOT_AFTER_PWM + 6,
  FR_SLOT_I2C_WRITE_REG16 = FR_SLOT_AFTER_PWM + 7,
  FR_SLOT_AFTER_I2C = FR_SLOT_AFTER_PWM + 8,
#else
  FR_SLOT_AFTER_I2C = FR_SLOT_AFTER_PWM,
#endif
#if FR_FEATURE_MATH
  FR_SLOT_ABS = FR_SLOT_AFTER_I2C,
  FR_SLOT_MIN = FR_SLOT_AFTER_I2C + 1,
  FR_SLOT_MAX = FR_SLOT_AFTER_I2C + 2,
  FR_SLOT_CLAMP = FR_SLOT_AFTER_I2C + 3,
  FR_SLOT_MAP = FR_SLOT_AFTER_I2C + 4,
  FR_SLOT_MOD = FR_SLOT_AFTER_I2C + 5,
  FR_SLOT_SQRT = FR_SLOT_AFTER_I2C + 6,
  FR_SLOT_AFTER_MATH = FR_SLOT_AFTER_I2C + 7,
#else
  FR_SLOT_AFTER_MATH = FR_SLOT_AFTER_I2C,
#endif
#if FR_FEATURE_PAD
  FR_SLOT_PAD_RESET = FR_SLOT_AFTER_MATH,
  FR_SLOT_PAD_EMIT_BYTE = FR_SLOT_AFTER_MATH + 1,
  FR_SLOT_PAD_LEN = FR_SLOT_AFTER_MATH + 2,
  FR_SLOT_PAD_TYPE = FR_SLOT_AFTER_MATH + 3,
  FR_SLOT_PAD_PEEK_BYTE = FR_SLOT_AFTER_MATH + 4,
#if FR_FEATURE_TEXT
  FR_SLOT_PAD_PACK = FR_SLOT_AFTER_MATH + 5,
  FR_SLOT_AFTER_PAD = FR_SLOT_AFTER_MATH + 6,
#else
  FR_SLOT_AFTER_PAD = FR_SLOT_AFTER_MATH + 5,
#endif
#else
  FR_SLOT_AFTER_PAD = FR_SLOT_AFTER_MATH,
#endif
#if FR_FEATURE_TEXT && FR_FEATURE_REPL
  FR_SLOT_TEXT_LENGTH = FR_SLOT_AFTER_PAD,
  FR_SLOT_TEXT_EQUALS_P = FR_SLOT_AFTER_PAD + 1,
  FR_SLOT_TEXT_CONCAT = FR_SLOT_AFTER_PAD + 2,
  FR_SLOT_TEXT_AT = FR_SLOT_AFTER_PAD + 3,
  FR_SLOT_TEXT_FROM_INT = FR_SLOT_AFTER_PAD + 4,
  FR_SLOT_PRINT = FR_SLOT_AFTER_PAD + 5,
  FR_SLOT_AFTER_TEXT = FR_SLOT_AFTER_PAD + 6,
#elif FR_FEATURE_TEXT
  FR_SLOT_TEXT_LENGTH = FR_SLOT_AFTER_PAD,
  FR_SLOT_TEXT_EQUALS_P = FR_SLOT_AFTER_PAD + 1,
  FR_SLOT_TEXT_CONCAT = FR_SLOT_AFTER_PAD + 2,
  FR_SLOT_TEXT_AT = FR_SLOT_AFTER_PAD + 3,
  FR_SLOT_TEXT_FROM_INT = FR_SLOT_AFTER_PAD + 4,
  FR_SLOT_AFTER_TEXT = FR_SLOT_AFTER_PAD + 5,
#else
  FR_SLOT_AFTER_TEXT = FR_SLOT_AFTER_PAD,
#endif
  FR_SLOT_EVENT_REGISTER = FR_SLOT_AFTER_TEXT,
  FR_SLOT_EVENT_CANCEL = FR_SLOT_AFTER_TEXT + 1,
  FR_SLOT_AFTER_EVENT = FR_SLOT_AFTER_TEXT + 2,
#if FR_FEATURE_NET
  FR_SLOT_WIFI_SAVE = FR_SLOT_AFTER_EVENT,
  FR_SLOT_WIFI_CONNECT = FR_SLOT_AFTER_EVENT + 1,
  FR_SLOT_WIFI_READY_P = FR_SLOT_AFTER_EVENT + 2,
  FR_SLOT_HTTP_GET = FR_SLOT_AFTER_EVENT + 3,
  FR_SLOT_TCP_OPEN = FR_SLOT_AFTER_EVENT + 4,
  FR_SLOT_TCP_READ = FR_SLOT_AFTER_EVENT + 5,
  FR_SLOT_TCP_WRITE = FR_SLOT_AFTER_EVENT + 6,
  FR_SLOT_TCP_CLOSE = FR_SLOT_AFTER_EVENT + 7,
  FR_SLOT_TCP_BYTES_READY_P = FR_SLOT_AFTER_EVENT + 8,
  FR_SLOT_AFTER_NET = FR_SLOT_AFTER_EVENT + 9,
#else
  FR_SLOT_AFTER_NET = FR_SLOT_AFTER_EVENT,
#endif
#if FR_FEATURE_POWER
  FR_SLOT_WATCHDOG_ARM = FR_SLOT_AFTER_NET,
  FR_SLOT_WATCHDOG_FEED = FR_SLOT_AFTER_NET + 1,
  FR_SLOT_SLEEP_DEEP = FR_SLOT_AFTER_NET + 2,
  FR_SLOT_SLEEP_WAKE_ON_GPIO = FR_SLOT_AFTER_NET + 3,
  FR_SLOT_AFTER_POWER = FR_SLOT_AFTER_NET + 4,
#else
  FR_SLOT_AFTER_POWER = FR_SLOT_AFTER_NET,
#endif
#if FR_FEATURE_BYTES
  FR_SLOT_BYTES_FROM_TEXT = FR_SLOT_AFTER_POWER,
  FR_SLOT_BYTES_FROM_BYTE = FR_SLOT_AFTER_POWER + 1,
  FR_SLOT_BYTES_FROM_INT = FR_SLOT_AFTER_POWER + 2,
  FR_SLOT_BYTES_LENGTH = FR_SLOT_AFTER_POWER + 3,
  FR_SLOT_BYTES_AT = FR_SLOT_AFTER_POWER + 4,
  FR_SLOT_BYTES_EQUALS_P = FR_SLOT_AFTER_POWER + 5,
  FR_SLOT_BYTES_CONCAT = FR_SLOT_AFTER_POWER + 6,
  FR_SLOT_TEXT_PACK = FR_SLOT_AFTER_POWER + 7,
  FR_SLOT_AFTER_BYTES = FR_SLOT_AFTER_POWER + 8,
#else
  FR_SLOT_AFTER_BYTES = FR_SLOT_AFTER_POWER,
#endif
#if FR_FEATURE_TRACE
  FR_SLOT_TRACE_OPEN = FR_SLOT_AFTER_BYTES,
  FR_SLOT_TRACE_WATCH = FR_SLOT_AFTER_BYTES + 1,
  FR_SLOT_TRACE_ARM = FR_SLOT_AFTER_BYTES + 2,
  FR_SLOT_TRACE_WAIT = FR_SLOT_AFTER_BYTES + 3,
  FR_SLOT_TRACE_STOP = FR_SLOT_AFTER_BYTES + 4,
  FR_SLOT_TRACE_COUNT = FR_SLOT_AFTER_BYTES + 5,
  FR_SLOT_TRACE_CHANNEL = FR_SLOT_AFTER_BYTES + 6,
  FR_SLOT_TRACE_LEVEL = FR_SLOT_AFTER_BYTES + 7,
  FR_SLOT_TRACE_DELTA_NS = FR_SLOT_AFTER_BYTES + 8,
  FR_SLOT_TRACE_COMPLETE_P = FR_SLOT_AFTER_BYTES + 9,
  FR_SLOT_TRACE_DUMP = FR_SLOT_AFTER_BYTES + 10,
  FR_SLOT_TRACE_CLOSE = FR_SLOT_AFTER_BYTES + 11,
  FR_SLOT_AFTER_TRACE = FR_SLOT_AFTER_BYTES + 12,
#else
  FR_SLOT_AFTER_TRACE = FR_SLOT_AFTER_BYTES,
#endif
#if FR_FEATURE_PULSE
  FR_SLOT_PULSE_OPEN = FR_SLOT_AFTER_TRACE,
  FR_SLOT_PULSE_ADD = FR_SLOT_AFTER_TRACE + 1,
  FR_SLOT_PULSE_CLEAR = FR_SLOT_AFTER_TRACE + 2,
  FR_SLOT_PULSE_COUNT = FR_SLOT_AFTER_TRACE + 3,
  FR_SLOT_PULSE_LEVEL = FR_SLOT_AFTER_TRACE + 4,
  FR_SLOT_PULSE_DURATION_NS = FR_SLOT_AFTER_TRACE + 5,
  FR_SLOT_PULSE_DUMP = FR_SLOT_AFTER_TRACE + 6,
  FR_SLOT_PULSE_PLAY = FR_SLOT_AFTER_TRACE + 7,
  FR_SLOT_PULSE_CLOSE = FR_SLOT_AFTER_TRACE + 8,
  FR_SLOT_AFTER_PULSE = FR_SLOT_AFTER_TRACE + 9,
#else
  FR_SLOT_AFTER_PULSE = FR_SLOT_AFTER_TRACE,
#endif
#if FR_FEATURE_REPL && FR_FEATURE_BYTES
  FR_SLOT_CONSOLE_READ_LINE = FR_SLOT_AFTER_PULSE,
  FR_SLOT_AFTER_CONSOLE_INPUT = FR_SLOT_AFTER_PULSE + 1,
#else
  FR_SLOT_AFTER_CONSOLE_INPUT = FR_SLOT_AFTER_PULSE,
#endif
#if FR_FEATURE_CONSOLE_ROUTING
  FR_SLOT_CONSOLE_UART = FR_SLOT_AFTER_CONSOLE_INPUT,
  FR_SLOT_CONSOLE_DEFAULT = FR_SLOT_AFTER_CONSOLE_INPUT + 1,
  FR_SLOT_CONSOLE_INFO = FR_SLOT_AFTER_CONSOLE_INPUT + 2,
  FR_SLOT_AFTER_CONSOLE = FR_SLOT_AFTER_CONSOLE_INPUT + 3,
#else
  FR_SLOT_AFTER_CONSOLE = FR_SLOT_AFTER_CONSOLE_INPUT,
#endif
#if FR_FEATURE_BLE
  FR_SLOT_BLE_ON = FR_SLOT_AFTER_CONSOLE,
  FR_SLOT_BLE_INFO = FR_SLOT_AFTER_CONSOLE + 1,
  FR_SLOT_BLE_OFF = FR_SLOT_AFTER_CONSOLE + 2,
#if FR_BLE_ENABLE_OBSERVER
  FR_SLOT_BLE_SCAN_START = FR_SLOT_AFTER_CONSOLE + 3,
  FR_SLOT_BLE_SCAN_STOP = FR_SLOT_AFTER_CONSOLE + 4,
  FR_SLOT_BLE_SCAN_NEXT = FR_SLOT_AFTER_CONSOLE + 5,
  FR_SLOT_BLE_SCAN_RSSI = FR_SLOT_AFTER_CONSOLE + 6,
  FR_SLOT_BLE_SCAN_PEER = FR_SLOT_AFTER_CONSOLE + 7,
  FR_SLOT_BLE_SCAN_FLAGS = FR_SLOT_AFTER_CONSOLE + 8,
  FR_SLOT_BLE_SCAN_DATA = FR_SLOT_AFTER_CONSOLE + 9,
  FR_SLOT_AFTER_BLE_OBSERVER = FR_SLOT_AFTER_CONSOLE + 10,
#else
  FR_SLOT_AFTER_BLE_OBSERVER = FR_SLOT_AFTER_CONSOLE + 3,
#endif
#if FR_BLE_ENABLE_BROADCASTER
  FR_SLOT_BLE_ADVERTISE_START = FR_SLOT_AFTER_BLE_OBSERVER,
  FR_SLOT_BLE_ADVERTISE_STOP = FR_SLOT_AFTER_BLE_OBSERVER + 1,
  FR_SLOT_AFTER_BLE_BROADCASTER = FR_SLOT_AFTER_BLE_OBSERVER + 2,
#else
  FR_SLOT_AFTER_BLE_BROADCASTER = FR_SLOT_AFTER_BLE_OBSERVER,
#endif
#if FR_BLE_ENABLE_CENTRAL
  FR_SLOT_BLE_CONNECT = FR_SLOT_AFTER_BLE_BROADCASTER,
  FR_SLOT_AFTER_BLE_CENTRAL = FR_SLOT_AFTER_BLE_BROADCASTER + 1,
#else
  FR_SLOT_AFTER_BLE_CENTRAL = FR_SLOT_AFTER_BLE_BROADCASTER,
#endif
#if FR_BLE_ENABLE_PERIPHERAL
  FR_SLOT_BLE_ACCEPT = FR_SLOT_AFTER_BLE_CENTRAL,
  FR_SLOT_AFTER_BLE_PERIPHERAL = FR_SLOT_AFTER_BLE_CENTRAL + 1,
#else
  FR_SLOT_AFTER_BLE_PERIPHERAL = FR_SLOT_AFTER_BLE_CENTRAL,
#endif
#if FR_BLE_ENABLE_CENTRAL || FR_BLE_ENABLE_PERIPHERAL
  FR_SLOT_BLE_CONNECTION_READY = FR_SLOT_AFTER_BLE_PERIPHERAL,
  FR_SLOT_BLE_CONNECTION_CLOSE = FR_SLOT_AFTER_BLE_PERIPHERAL + 1,
  FR_SLOT_BLE_CONNECTION_INFO = FR_SLOT_AFTER_BLE_PERIPHERAL + 2,
  FR_SLOT_BLE_CONNECTION_RSSI = FR_SLOT_AFTER_BLE_PERIPHERAL + 3,
  FR_SLOT_BLE_CONNECTION_PARAMS = FR_SLOT_AFTER_BLE_PERIPHERAL + 4,
  FR_SLOT_BLE_CONNECTION_MTU = FR_SLOT_AFTER_BLE_PERIPHERAL + 5,
  FR_SLOT_AFTER_BLE_CONNECTION = FR_SLOT_AFTER_BLE_PERIPHERAL + 6,
#else
  FR_SLOT_AFTER_BLE_CONNECTION = FR_SLOT_AFTER_BLE_PERIPHERAL,
#endif
#if FR_BLE_ENABLE_GATT_SERVER
  FR_SLOT_BLE_GATT_SERVICE = FR_SLOT_AFTER_BLE_CONNECTION,
  FR_SLOT_BLE_GATT_CHARACTERISTIC = FR_SLOT_AFTER_BLE_CONNECTION + 1,
  FR_SLOT_BLE_GATT_PRIMARY = FR_SLOT_AFTER_BLE_CONNECTION + 2,
  FR_SLOT_BLE_GATT_SECONDARY = FR_SLOT_AFTER_BLE_CONNECTION + 3,
  FR_SLOT_BLE_GATT_READ = FR_SLOT_AFTER_BLE_CONNECTION + 4,
  FR_SLOT_BLE_GATT_WRITE = FR_SLOT_AFTER_BLE_CONNECTION + 5,
  FR_SLOT_BLE_GATT_WRITE_COMMAND = FR_SLOT_AFTER_BLE_CONNECTION + 6,
  FR_SLOT_BLE_GATT_NOTIFY_FLAG = FR_SLOT_AFTER_BLE_CONNECTION + 7,
  FR_SLOT_BLE_GATT_INDICATE_FLAG = FR_SLOT_AFTER_BLE_CONNECTION + 8,
  FR_SLOT_BLE_GATT_READ_ENCRYPTED = FR_SLOT_AFTER_BLE_CONNECTION + 9,
  FR_SLOT_BLE_GATT_WRITE_ENCRYPTED = FR_SLOT_AFTER_BLE_CONNECTION + 10,
  FR_SLOT_BLE_GATT_READ_AUTHENTICATED = FR_SLOT_AFTER_BLE_CONNECTION + 11,
  FR_SLOT_BLE_GATT_WRITE_AUTHENTICATED = FR_SLOT_AFTER_BLE_CONNECTION + 12,
  FR_SLOT_AFTER_BLE_GATT_LITERALS = FR_SLOT_AFTER_BLE_CONNECTION + 13,
  FR_SLOT_BLE_GATT_INSTALL = FR_SLOT_AFTER_BLE_GATT_LITERALS,
  FR_SLOT_BLE_GATT_INFO = FR_SLOT_AFTER_BLE_GATT_LITERALS + 1,
  FR_SLOT_BLE_GATT_SET = FR_SLOT_AFTER_BLE_GATT_LITERALS + 2,
  FR_SLOT_BLE_GATT_GET = FR_SLOT_AFTER_BLE_GATT_LITERALS + 3,
  FR_SLOT_BLE_GATT_NOTIFY = FR_SLOT_AFTER_BLE_GATT_LITERALS + 4,
  FR_SLOT_BLE_GATT_INDICATE = FR_SLOT_AFTER_BLE_GATT_LITERALS + 5,
  FR_SLOT_BLE_GATT_NEXT_WRITE = FR_SLOT_AFTER_BLE_GATT_LITERALS + 6,
  FR_SLOT_BLE_GATT_WRITE_ATTRIBUTE = FR_SLOT_AFTER_BLE_GATT_LITERALS + 7,
  FR_SLOT_BLE_GATT_WRITE_DATA = FR_SLOT_AFTER_BLE_GATT_LITERALS + 8,
  FR_SLOT_AFTER_BLE_GATT_SERVER = FR_SLOT_AFTER_BLE_GATT_LITERALS + 9,
#elif FR_BLE_ENABLE_GATT_CLIENT
  FR_SLOT_BLE_GATT_INFO = FR_SLOT_AFTER_BLE_CONNECTION,
  FR_SLOT_AFTER_BLE_GATT_SERVER = FR_SLOT_AFTER_BLE_CONNECTION + 1,
#else
  FR_SLOT_AFTER_BLE_GATT_SERVER = FR_SLOT_AFTER_BLE_CONNECTION,
#endif
#if FR_BLE_ENABLE_GATT_CLIENT
  FR_SLOT_BLE_GATT_NOTIFICATIONS = FR_SLOT_AFTER_BLE_GATT_SERVER,
  FR_SLOT_BLE_GATT_INDICATIONS = FR_SLOT_AFTER_BLE_GATT_SERVER + 1,
  FR_SLOT_BLE_GATT_FIND = FR_SLOT_AFTER_BLE_GATT_SERVER + 2,
  FR_SLOT_BLE_GATT_CLIENT_READ = FR_SLOT_AFTER_BLE_GATT_SERVER + 3,
  FR_SLOT_BLE_GATT_CLIENT_WRITE = FR_SLOT_AFTER_BLE_GATT_SERVER + 4,
  FR_SLOT_BLE_GATT_SUBSCRIBE = FR_SLOT_AFTER_BLE_GATT_SERVER + 5,
  FR_SLOT_BLE_GATT_UNSUBSCRIBE = FR_SLOT_AFTER_BLE_GATT_SERVER + 6,
  FR_SLOT_BLE_GATT_NEXT_NOTIFICATION = FR_SLOT_AFTER_BLE_GATT_SERVER + 7,
  FR_SLOT_BLE_GATT_NOTIFICATION_ATTRIBUTE =
      FR_SLOT_AFTER_BLE_GATT_SERVER + 8,
  FR_SLOT_BLE_GATT_NOTIFICATION_DATA = FR_SLOT_AFTER_BLE_GATT_SERVER + 9,
  FR_SLOT_AFTER_BLE = FR_SLOT_AFTER_BLE_GATT_SERVER + 10,
#else
  FR_SLOT_AFTER_BLE = FR_SLOT_AFTER_BLE_GATT_SERVER,
#endif
#else
  FR_SLOT_AFTER_BLE = FR_SLOT_AFTER_CONSOLE,
#endif
#if FR_FEATURE_TEXT
  FR_SLOT_FROTHY_RELEASE = FR_SLOT_AFTER_BLE,
  FR_SLOT_AFTER_RELEASE = FR_SLOT_AFTER_BLE + 1,
#else
  FR_SLOT_AFTER_RELEASE = FR_SLOT_AFTER_BLE,
#endif
#if FR_INCLUDE_TEST_NATIVES && FR_FEATURE_TEXT
  FR_SLOT_FIRE_EVENT = FR_SLOT_AFTER_RELEASE,
  FR_SLOT_BOARD_CAPABILITY_BASE = FR_SLOT_AFTER_RELEASE + 1,
#else
  FR_SLOT_BOARD_CAPABILITY_BASE = FR_SLOT_AFTER_RELEASE,
#endif
  FR_SLOT_LED_ACTIVE_LEVEL = FR_SLOT_BOARD_CAPABILITY_BASE,
  FR_SLOT_BOARD_LOCAL_BASE = FR_SLOT_BOARD_CAPABILITY_BASE + 1,
};

#if FR_SLOT_BOARD_LOCAL_BASE > FR_PROFILE_MAX_SLOTS
#error "base slot contract exceeds FR_PROFILE_MAX_SLOTS"
#endif

typedef enum fr_base_layer_t {
  FR_BASE_LAYER_CORE,
  FR_BASE_LAYER_TARGET,
  FR_BASE_LAYER_BOARD,
  FR_BASE_LAYER_SOURCE,
  FR_BASE_LAYER_PERSISTENCE,
} fr_base_layer_t;

typedef enum fr_base_def_kind_t {
  FR_BASE_DEF_LITERAL,
  FR_BASE_DEF_NATIVE,
} fr_base_def_kind_t;

typedef struct fr_base_def_t {
  fr_slot_id_t slot_id;
#if FR_BASE_IMAGE_INCLUDE_SYMBOLS
  const char *name;
  const char *alias;
#endif
  fr_base_def_kind_t kind;
  fr_tagged_t literal_tagged;
  fr_native_fn_t native_fn;
  uint8_t native_arity;
#if FR_FEATURE_NATIVE_SIGNATURES
  const fr_native_signature_t *native_signature;
#endif
} fr_base_def_t;

typedef struct fr_base_def_layer_t {
  fr_base_layer_t layer;
  const fr_base_def_t *defs;
  uint16_t count;
} fr_base_def_layer_t;

extern const fr_base_def_t fr_target_base_defs[];
extern const uint16_t fr_target_base_def_count;
extern const fr_base_def_t fr_board_base_defs[];
extern const uint16_t fr_board_base_def_count;

#if FR_FEATURE_PERSISTENCE
/* True for the native `save` is bound to, however it was reached. */
bool fr_base_native_is_save(const fr_native_entry_t *entry);
#endif

uint16_t fr_base_def_layer_count(void);
fr_err_t fr_base_def_layer_at(uint16_t index,
                              fr_base_def_layer_t *out_layer);
uint16_t fr_base_def_count(void);
fr_err_t fr_base_def_at(uint16_t index, const fr_base_def_t **out_def,
                        fr_base_layer_t *out_layer);
fr_err_t fr_base_def_for_slot(fr_slot_id_t slot_id,
                              const fr_base_def_t **out_def,
                              fr_base_layer_t *out_layer);

uint16_t fr_base_slot_count(void);
const char *fr_base_slot_name_at(uint16_t index);
const char *fr_base_slot_name(fr_slot_id_t slot_id);
fr_err_t fr_base_slot_id_for_name(const char *name, fr_slot_id_t *out_slot_id);
fr_err_t fr_base_slot_layer(fr_slot_id_t slot_id,
                            fr_base_layer_t *out_layer);
fr_err_t fr_base_slot_ref(fr_slot_id_t slot_id, fr_image_ref_t *out_ref);

#if FR_FEATURE_SOURCE_BASE
/* Runtime record of slots bound from base/core.frothy at boot. Owned by
   base_image.c; base_defs reads it so source words report their layer. */
void fr_base_source_record_reset(void);
fr_err_t fr_base_source_record_add(fr_slot_id_t slot_id, const char *name);
bool fr_base_is_source_slot(fr_slot_id_t slot_id);
const char *fr_base_source_slot_name(fr_slot_id_t slot_id);
fr_err_t fr_base_source_slot_id_for_name(const char *name,
                                         fr_slot_id_t *out_slot_id);
uint16_t fr_base_source_record_count(void);
fr_err_t fr_base_source_record_slot_id_at(uint16_t index,
                                          fr_slot_id_t *out_slot_id);
#endif
