#pragma once

#include "froth_types.h"

enum {
  FROTHY_CONTROL_HELLO_REQ = 0x01,
  FROTHY_CONTROL_HELLO_EVT = 0x02,
  FROTHY_CONTROL_EVAL_REQ = 0x03,
  FROTHY_CONTROL_WORDS_REQ = 0x04,
  FROTHY_CONTROL_SEE_REQ = 0x05,
  FROTHY_CONTROL_DETACH_REQ = 0x06,
  FROTHY_CONTROL_RESET_REQ = 0x07,
  FROTHY_CONTROL_OUTPUT_EVT = 0x10,
  FROTHY_CONTROL_VALUE_EVT = 0x11,
  FROTHY_CONTROL_ERROR_EVT = 0x12,
  FROTHY_CONTROL_INTERRUPTED_EVT = 0x13,
  FROTHY_CONTROL_IDLE_EVT = 0x14,
};

typedef enum {
  FROTHY_CONTROL_PHASE_CONTROL = 1,
  FROTHY_CONTROL_PHASE_PARSE = 2,
  FROTHY_CONTROL_PHASE_EVAL = 3,
  FROTHY_CONTROL_PHASE_INSPECT = 4,
} frothy_control_phase_t;

froth_error_t frothy_control_run(void);
